releaseType: java-yoshi
bumpMinorPreMajor: true
handleGHRelease: true
branches:
  - branch: bigtable-1.x
    releaseType: java-yoshi
    bumpMinorPreMajor: true
    handleGHRelease: true
  - releaseType: java-lts
    bumpMinorPreMajor: true
    handleGHRelease: true
    branch: 1.20.0-sp
